#!/bin/bash

#Set -x nos muestra los comandos ejecutados a la hora de ejecutar el propio script
set -x

#Actualizamos el sistema
sudo apt update

#Upgradeamos el sistema
sudo apt upgrade -y

#Nos instalamos apache
sudo apt install apache2 -yq

#Nos instalamos isc-dhcp-server
sudo apt install isc-dhcp-server -yq

#Deshabilitamos el servicio NetworkManager
sudo systemctl disable NetworkManager
sudo systemctl stop NetworkManager

#Copiamos la información en el fichero /etc/network/interfaces
sudo bash -c 'cat <<EOF> /etc/network/interfaces

source /etc/network/interfaces.d/*
#The loopback network interface
auto lo
iface lo inet loopback
#Red principal
auto enp0s3
iface enp0s3 inet static
address 172.26.20.101
netmask 255.255.0.0
gateway 172.26.0.1
#Red secundaria
auto enp0s8
iface enp0s8 inet static
address 192.168.1.2
netmask 255.255.255.0
EOF'

#Reiniciamos el servicio de la red
systemctl restart networking

#Copiamos la información en el fichero /etc/resolv.conf
sudo bash -c 'cat <<EOF> /etc/resolv.conf

#Generated by NetworkManager
nameserver 8.8.8.8
EOF'

#Copiamos la información en el fichero /etc/default/isc-dhcp-server
sudo bash -c 'cat <<EOF> /etc/default/isc-dhcp-server

INTERFACESv4="enp0s8"
INTERFACESv6=""
EOF'

#Copiamos la información en el fichero /etc/dhcp/dhcpd.conf
sudo bash -c 'cat <<EOF> /etc/dhcp/dhcpd.conf

option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;

default-lease-time 600;
max-lease-time 7200;

ddns-update-style none;

authoritative;
ddns-update-style none;

failover peer "FAILOVER" {
primary;
address 192.168.1.2;
port 647;
peer address 192.168.1.3;
peer port 647;
max-unacked-updates 10;
max-response-delay 30;
load balance max seconds 3;
mclt 1800;
split 128;
}

subnet 192.168.1.0 netmask 255.255.255.0 {
option broadcast-address 192.168.1.255;
option routers 192.168.1.2;
option domain-name-servers 8.8.8.8, 8.8.4.4;
pool {
failover peer "FAILOVER";
max-lease-time 3600;
range 192.168.1.10 192.168.1.50;
}
}
EOF'

#Reiniciamos el servicio isc-dhcp-server
systemctl restart isc-dhcp-server 
